export const AppConstants = {
  ADD: "Add",
  ADD_A_BOOK: "Add a book",
  AND: "and",
  APP_TITLE: "Bookie",
  CANCEL: "Cancel",
  CLOSE: "Close",
  CONTAINED: "contained",
  DELETE: "Delete",
  EDIT: "Edit",
  EDIT_A_BOOK: "Edit a book",
  ENTER_ISBN: "Enter ISBN here",
  ENTER_NOTES: "Enter notes here",
  ENTER_TITLE: "Enter title here",
  ERROR: "Error: ",
  ERROR_PROCESSING: "Pst! There was an error trying to process your request.",
  EXCLAMATION_POINT: "!",
  FOUR_SECONDS: 4000,
  HOME: "Home",
  ISBN: "ISBN",
  ISBN_LOWERCASE: "isbn",
  ISBN_REQUIRED: "ISBN *",
  NORMAL: "normal",
  NOTES: "Notes",
  NOTES_LOWERCASE: "notes",
  OUTLINED: "outlined",
  PRIMARY: "primary",
  REQUIRED_MSG_HEADER: "Pst! You're missing some required stuff.",
  SECONDARY: "secondary",
  SUBMIT: "Submit",
  TITLE: "Title",
  TITLE_LOWERCASE: "title",
  TITLE_REQUIRED: "Title *",
  VIEW: "View",
  VIEW_A_BOOK: "View a book",
  YOU_FORGOT_TO: "You forgot to add ",
};
